### ISSUE TITLE
[StreamingStreamer] 로직 수정 및 보충 요청

### ISSUE THREAD

**Issue by sno0ow-p** [netproj-team6/skku_chat#4]
## helper
https://github.com/netproj-team6/skku_chat/blob/1113a416c6cf3e7284b95c33810c23b637310fbc/server/server-helper.cc#L27-L30

파라미터로 받아온 port를 설정하는 부분 추가가 필요할 것 같습니다.

https://github.com/netproj-team6/skku_chat/blob/1113a416c6cf3e7284b95c33810c23b637310fbc/server/server.h#L55-L56

위와 같이, 소스 코드에 구현되어 있지 않은 메서드가 존재하는 것 같습니다.

## server
https://github.com/netproj-team6/skku_chat/blob/1113a416c6cf3e7284b95c33810c23b637310fbc/server/server.cc#L121-L140

https://github.com/netproj-team6/skku_chat/blob/1113a416c6cf3e7284b95c33810c23b637310fbc/server/server.cc#L222-L245

위의 두 코드 부분을 보았을 때, m_peerAddress와 m_peerPort는 LB 로 부터 패킷을 받을 때 설정되는 값이며 런타임 중에 변경될 수 있는 값으로 보입니다.

그러나 StartApplication() 메서드에서 m_peerAddress를 이용해 검증하는 로직이 있어서, 아마 저기서 에러가 나지 않을까 생각이 듭니다.

그래서 이 부분 수정이 필요할 것 같다는 생각이 드는데요,

https://github.com/netproj-team6/skku_chat/blob/1113a416c6cf3e7284b95c33810c23b637310fbc/server/server.cc#L198-L220

```
LoadBalancerHeader header;
packet->PeekHeader(header)
uint32_t clientAddress = header.GetIpv4Address();
uint16_t clientPort = header.GetPort();
InetSocketAddress clientAddress(Ipv4Address(clientAddress), clientPort);
```
위 부분을 HandleRead() 메서드가 아닌, Send() 메서드에서 호출하도록 변경되어야 할 것 같습니다.

그리고 Send() 메서드에서 패킷을 보내는 부분은 아래처럼 수정되어야 할 것 같습니다.

```
socket->SendTo(packet, 0, clientAddress);
```

추가로, isPause도 객체 필드값으로 선언되어서 이 또한 Send() 메서드에서 값을 받도록 바꿔야 하지 않을까 싶습니다.

**Comment by DormunDoorlock** [comment]
1. Helper 부분 port 부분 추가, 수정 완료했습니다. 서버내 포트가 시나리오파일에서 정한 포트로 들어간 것을 확인했습니다.(ex. 현재 2020)
2. 해당 부분은 오류가 맞습니다. StreamingStreamer::HandleRead가 실행되기 전에, Address 검증 로직에 들어가서 오류가 발생합니다.
수정사항 :  일단 패킷을 받은 후에 m_socket을 생성하는 방법으로 수정하였습니다. 즉, HandleRead에서 헤더 내 클라이언트 주소와 포트  확인 후 전송 과정을 거쳤습니다.
