### ISSUE TITLE
load balance의 target address의 유효성

### ISSUE THREAD

**Issue by Qayin-PJS** [netproj-team6/skku_chat#5]
LoadBalancer::AssignTargetAddress 함수에서 target을 IPv4로 변환하면 error 가 나는 경우가 생기는데, target이 유요한지 확인 바랍니다.

![image](https://user-images.githubusercontent.com/62598120/171215751-9c6a807e-27ee-48c9-a3f5-9251ed5f0514.png)

![image](https://user-images.githubusercontent.com/62598120/171215798-b5a465c3-0b2e-4a87-9145-8804ced692e7.png)

**Comment by Qayin-PJS** [comment]
load balance의 주소 할당 방식을 ipv4로 변경 가능할까요?

**Comment by Qayin-PJS** [comment]
InetSocketAddress::ConvertFrom(target).GetIpv4()

**Comment by sno0ow-p** [comment]
우선 저 함수의 역할을 먼저 설명드리겠습니다.

AssignTargetAddress는 클라이언트의 Ipv4 Address가 정수형으로 변환된 값을 파라미터 `from` 변수로 전달 받습니다.
즉 `from` 변수가 가리키는 값은 패킷 헤더에서 바이트 형태로 Serialized되어 있는 클라이언트의 주소 입니다.

클라이언트 주소를 토대로 특정 알고리즘을 통해 서버의 주소를 받아 옵니다. 그 값이 `target` 변수에 저장이 되는 것이구요. 이 `target` 변수는 처음 애플리케이션이 시작될 때 저장된 자료형을 반환합니다.
아래가 `StartApplication()` 함수 내에서 스트리밍 서버 주소를 저장하는 부분입니다.
https://github.com/netproj-team6/Video_Streamer/blob/d2cc8191df01480239f1aa5a693d103fbe123cd0/lb/load-balancer.cc#L131-L133

그리고 `AssignTargetAddress()` 함수를 호출하여 반환받은 스트리밍 서버 주소로 패킷을 보내게 됩니다.
https://github.com/netproj-team6/Video_Streamer/blob/d2cc8191df01480239f1aa5a693d103fbe123cd0/lb/load-balancer.cc#L184-L185
